package com.off.admin.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table student
 */
public class Student implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sno
     *
     * @mbg.generated
     */
    private Integer sno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.cno
     *
     * @mbg.generated
     */
    private Integer cno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sname
     *
     * @mbg.generated
     */
    private String sname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sage
     *
     * @mbg.generated
     */
    private String sage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.deletes
     *
     * @mbg.generated
     */
    private Integer deletes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sno
     *
     * @return the value of student.sno
     *
     * @mbg.generated
     */
    public Integer getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sno
     *
     * @param sno the value for student.sno
     *
     * @mbg.generated
     */
    public void setSno(Integer sno) {
        this.sno = sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.cno
     *
     * @return the value of student.cno
     *
     * @mbg.generated
     */
    public Integer getCno() {
        return cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.cno
     *
     * @param cno the value for student.cno
     *
     * @mbg.generated
     */
    public void setCno(Integer cno) {
        this.cno = cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sname
     *
     * @return the value of student.sname
     *
     * @mbg.generated
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sname
     *
     * @param sname the value for student.sname
     *
     * @mbg.generated
     */
    public void setSname(String sname) {
        this.sname = sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sage
     *
     * @return the value of student.sage
     *
     * @mbg.generated
     */
    public String getSage() {
        return sage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sage
     *
     * @param sage the value for student.sage
     *
     * @mbg.generated
     */
    public void setSage(String sage) {
        this.sage = sage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.deletes
     *
     * @return the value of student.deletes
     *
     * @mbg.generated
     */
    public Integer getDeletes() {
        return deletes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.deletes
     *
     * @param deletes the value for student.deletes
     *
     * @mbg.generated
     */
    public void setDeletes(Integer deletes) {
        this.deletes = deletes;
    }
}